redis:
  addr: "127.0.0.1:6379"
  username: "data_kernel"
  password: "CHANGE_ME_STRONG"
  db: 0
  key_prefix: "fdc:"

producer:
  name: "demo-producer"
  contact: "demo@example.com"
  send_interval_ms: 1000
  # Registration signing keys (producer identity)
  ssh_private_key_file: "./modules.d/producer-example/ssh/id_ed25519"
  ssh_public_key_file: "./modules.d/producer-example/ssh/id_ed25519.pub"
  # If you use producer SSH certificates, set the certificate file too (signed by producer CA)
  ssh_cert_file: "./modules.d/producer-example/ssh/id_ed25519-cert.pub"
  # Schema provisioning
  subject_key: "DEMO-1"
  # One of the following schema references must be provided for set_current:
  #   schema_id: "<uuid>"
  #   schema_name: "<name>" and schema_version: <int>
  # For upgrade_auto (atomic create+set_current), provide schema_name and schema_body
  schema_id: ""
  schema_name: ""
  schema_version: 0
  # schema_body can be provided inline as JSON string
  schema_body: ""

