redis:
  addr: "127.0.0.1:6379"
  username: "data_kernel"
  password: "CHANGE_ME_STRONG"
  db: 0
  key_prefix: "fdc:"
  register_stream: "register"
  events_stream: "events"
  register_resp_stream: "register:resp"
  control_resp_stream: "control:resp"

producer:
  name: "demo-producer"
  contact: "demo@example.com"
  send_interval_ms: 1000
  # Registration identity (certificate-only, signed by Producer CA)
  # Certificate is REQUIRED. No fallback to raw SSH public key.
  ssh_private_key_file: "./modules.d/producer-example/ssh/id_ed25519"
  ssh_public_key_file: "./modules.d/producer-example/ssh/id_ed25519.pub"
  ssh_cert_file: "./modules.d/producer-example/ssh/id_ed25519-cert.pub"
  # Schema provisioning
  schema_name: "demo_schema"
  schema_version: 1
  subject_key: "DEMO-1"

