server:
  listen: ":7600"
  auth_token: "devtoken"
  max_message_bytes: 1048576
  read_timeout_ms: 15000
  allowed_origins: []
  window_size: 0
  ingest_queue_size: 8192

sinks:
  file:
    enabled: true
    directory: "./data"
    rotate_mb: 512
    rotate_daily: false
    compression: "none"

modules:
  dir: "./modules.d"

postgres:
  enabled: false
  dsn: "postgres://data_kernel:CHANGE_ME_STRONG@127.0.0.1:5432/data_kernel_db?sslmode=disable"
  max_conns: 8
  conn_max_lifetime_ms: 600000
  apply_migrations: true
  queue_size: 1024

redis:
  enabled: false
  addr: "127.0.0.1:6379"
  username: "data_kernel"
  password: "CHANGE_ME_STRONG"
  db: 0
  stream: "events"
  maxlen_approx: 1000000
  queue_size: 2048

logging:
  level: "info"
  buffer: 4096
  output: "stdout"

